### ISSUE TITLE
stuck in the center issue

### ISSUE THREAD

**Issue by cuihonglei** [swiftui-library/hstack-snap-to-scroll#2]
Hi there, 

I found an issue, if you scroll it fast in the beginning, it will stuck in the center sometimes. 

I know this is because of ScrollView. When you trigger the ScrollView's scrolling, the Views which are inside the ScrollView, cannot get the DragGesture anymore. But before that, they have already started part of the scrolling, so they cannot finish it. If you use other Containers, like LIst (it also has a similar vertical scrolling behavior), there's no problem like this. Do you have any idea about this?

You could have a look at the effect here.
https://jmp.sh/SdccqRX

Thanks.

**Comment by trentguillory** [comment]
Unfortunately, it looks like this is due to some internal SwiftUI issue in the combination of `ScrollView` and the `DragGesture` used in `HStackSnap`. The `.dragEnded` callback isn't firing in this scenario, so there's no clear way to have it snap to the correct location. 

But thanks for flagging this and reproducing it so clearly. I'll start considering some workarounds since the provided APIs fall short at the moment.
